### ISSUE TITLE
v3 roadmap

### ISSUE THREAD

**Issue by ahnl** [Testausserveri/matikkaeditori.fi#2]
Continuing from the current point with the following tasks:

- [x] Folders
    - [x] Creating folders in the filesystem (workers) @Esinko 
    - [x] Displaying folders in the app @ahnl 
    - [x] Navigating a folder up @ahnl 
    - [x] Breadcrumbs @ahnl 
- [ ] Drag and drop file tree @ahnl 
    - [ ] Moving files from folder to another (workers) @Esinko 
- [x] Deleting files and folders @ahnl @Esinko 
- [ ] Mobile UI @ahnl 
    - [ ] Math keyboard @ahnl 
- [ ] More links in the navigation bar
     - More like a design thing, Mikael has an idea of squiggly underlines for links
- [ ] Polish math editor 🇵🇱 
    - [x] Container stylings @ahnl 
    - [x] Moving with arrow keys @Esinko 
    - [ ] Picture support, rescaling, (+ additionally maybe dragging around) @Esinko 
    - [x] Discuss about whether we want an inline math editing or as it is currently
    - [ ] Wrapping long math equations @Esinko 
    - [x] Limit what kind of html user can paste into the editor
- [ ] Export formats
    - [ ] PDF export should have text as an actual text, it shouldn't be all A4 images of pages
    - [ ] Fix how content is wrapped from page to another in the PDF export, e.g. currently it can break mid-element and that's definitely bad
    - [ ] Watermarks @ahnl 
- [x] V1 -> V3 data migration @Esinko 
- [ ] Equation and special character sidebar: figure out how should we make it stick to the side while document is scrolled. The sections could possibly be collapsable. @ahnl 

You can edit this list and add more items, and tick out things that have been done.
